#include <iostream>
#include <cstdlib>
#include <vector>

#include "reader.h"

#define TEST 0
#define MLP 0
#define KNN 0
#define D_TREE 1
#define HSI 0
#define IRIS 0

std::string command_generation(std::string output_dir, std::string bin, std::string args, std::string cpu_params){
	std::ostringstream cmd;

	const std::string GEM5_PATH = "/home/ryann0097-blazebringer/Research/gem5/build/RISCV/gem5.opt";
	const std::string RISCV_PATH = "/home/ryann0097-blazebringer/Research/gem5/configs/Tests/Configs/RiscvDir.py";

	cmd << GEM5_PATH << " --outdir=" << output_dir << " " << RISCV_PATH;

	cmd << " --cmd " << bin;

	if(!args.empty()){
		cmd << " --opts " << args;
		cmd << " " << cpu_params;
	} else {
		cmd << " " << cpu_params;
	}

	return cmd.str();
}

void write_test_running_msg(std::string program, std::string args, std::string set){
	std::cout << "\n\n---------------------------------------------------\n";
	std::cout << "\nRUNNING >>> [ Program: " << program << " ]\n";
	if(!args.empty()){
		std::cout << "\n\t\t - Args: " << args << "\n";
	}
	std::cout << "\nCPU Set: " << set << "\n";
	std::cout << "\n---------------------------------------------------";
}

int main(){

    // Home user path
    const std::string BASE_PATH = "/home/ryann0097-blazebringer";

    // Applications and simulator path
	const std::string GEM5_EXEC_PATH = BASE_PATH + "/Research/gem5/build/RISCV/gem5.opt";
	const std::string BASE_RESEARCH_PATH = BASE_PATH + "/Research/ryan-ml-riscv-prof";
	const std::string RISCV_PATH = BASE_PATH +  "/Research/gem5/configs/Tests/Configs/RiscvDir.py";

    // Output and programs paths
	const std::string BASE_OUTPUT_DIR_PATH = BASE_RESEARCH_PATH + "/automation/output-tests";
	const std::string BASE_PROGRAM_PATH = BASE_RESEARCH_PATH + "/programs";

    // Binaries complement
	const std::string DECISION_TREE_BIN = BASE_PROGRAM_PATH + "/decision-tree";
	const std::string KNN_BIN = BASE_PROGRAM_PATH + "/k-nn";
	const std::string MLP_BIN = BASE_PROGRAM_PATH + "/mlp";

    // Output directories
	const std::string OUTPUT_MLP = BASE_PROGRAM_PATH + "/mlp-output/";
	const std::string OUTPUT_KNN = BASE_PROGRAM_PATH + "/knn-output/";
	const std::string OUTPUT_DT = BASE_PROGRAM_PATH + "/dt-output/";
	const std::string OUTPUT_HSI = BASE_PROGRAM_PATH + "/hsi-output/";
	const std::string OUTPUT_IRIS = BASE_PROGRAM_PATH + "/iris-output/";

    /**
     * Configurations file reader:
     * It will be useful to us to read the file that contains
     * the configurations generated by the LHS (Latin Hypercube Sampling).
     */

    ConfigReader reader;

    std::vector<Config>configs = reader.read(BASE_PATH + "/Research/ryan-ml-riscv-prof/automation/freal/todas_validas.txt");
    

    #if TEST

    std::string cur_bin = "/home/ryann0097-blazebringer/Research/gem5/configs/Tests/Bin/hello";
    std::string args = "";

    for(int i = 0; i < configs.size(); i++){
        std::string output_dir = "/home/ryann0097-blazebringer/Research/ryan-ml-riscv-prof/automation/freal/output/broke_program_test/config-" + std::to_string(i);
        write_test_running_msg("Broke Program", "", "Config-" + std::to_string(i));
        system(command_generation(output_dir, cur_bin, args, configs[i].config_to_args()).c_str());
    }
    
    #endif

    #if MLP

    std::string cur_bin = MLP_BIN + "/MLPTest";
    std::string args = "";
    for(int i = 0; i < configs.size(); i++){
        std::string output_dir = OUTPUT_MLP + "/config-" + std::to_string(i);
        write_test_running_msg("MLP", "", "config-" + std::to_string(i));
        system(command_generation(output_dir, cur_bin, args, configs[i].config_to_args()).c_str());
    }

    #endif

    #if HSI

    std::string cur_bin = MLP_BIN + "/HSIDatasetTest";
    std::string args = "1";
    for(int i = 0; i < configs.size(); i++){
        std::string output_dir = OUTPUT_HSI + "/config-" + std::to_string(i);
        write_test_running_msg("HSI", "", "config-" + std::to_string(i));
        system(command_generation(output_dir, cur_bin, args, configs[i].config_to_args()).c_str());
    }

    #endif 

    #if IRIS

    std::string cur_bin = MLP_BIN + "/IrisDatasetTest";
    std::string args = "1";
    for(int i = 0; i < configs.size(); i++){
        std::string output_dir = OUTPUT_IRIS + "/config-" + std::to_string(i);
        write_test_running_msg("Iris", "", "config-" + std::to_string(i));
        system(command_generation(output_dir, cur_bin, args, configs[i].config_to_args()).c_str());
        // std::cout << command_generation(output_dir, cur_bin, args, configs[i].config_to_args()) << std::endl;
    }

    #endif

    #if KNN

    std::string cur_bin = KNN_BIN + "/knn_riscv";
    std::string args = "X_train.txt X_test.txt X_result.txt";

    for(int i = 0; i < configs.size(); i++){
        std::string output_dir = OUTPUT_KNN + "/config-" + std::to_string(i);
        write_test_running_msg("K-nn", "", "config-" + std::to_string(i));
        system(command_generation(output_dir, cur_bin, args, configs[i].config_to_args()).c_str());
    }

    #endif

    #if D_TREE

    std::string cur_bin = DECISION_TREE_BIN + "/dt_riscv";
    std::string args = "";
    

    for(int i = 0; i < configs.size(); i++){
        std::string output_dir = OUTPUT_DT + "/config-" + std::to_string(i);
        write_test_running_msg("Decision Tree", "", "config-" + std::to_string(i));
        std::string args = DECISION_TREE_BIN + "/dt_train.txt " +
                           DECISION_TREE_BIN + "/dt_test.txt " +
                           DECISION_TREE_BIN + "/result" + std::to_string(i) + ".txt";
        system(command_generation(output_dir, cur_bin, args, configs[i].config_to_args()).c_str());
        //std::cout << command_generation(output_dir, cur_bin, args, configs[i].config_to_args()) << std::endl;

    }

    #endif
}
